SerpentesBlog/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('blog.urls')),
]

blog/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

from views import (
    index,
    PostListView,
    CommentCreateView,
    CommentEditView,
    CommentDeleteView,
    post_detail,
    PostCreateView,
    PostEditView,
    PostDeleteView,
    UserProfileView,
    UserProfileUpdateView,
    UserProfileCreateView,
    LoginView,
    RegisterView,
    LogoutView,
    UploadImage,
    
)

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^$', PostListView.as_view(), name='post_list'),
    url(r'^post/(?P<pk>[0-9]+)/create$', PostCreateView.as_view(), name='post_create'),
    url(r'^post/(?P<pk>[0-9]+)/edit$', PostEditView.as_view(), name='post_edit'),
    url(r'^post/(?P<pk>[0-9]+)$', post_detail, name='post_detail'),
    url(r'^post/(?P<pk>[0-9]+)/delete$', PostDeleteView.as_view(), name='post_delete'),
    url(r'^post/(?P<pk>[0-9]+)/comment/create$', CommentCreateView.as_view(), name='comment_create'),
    url(r'^userprofile/(?P<pk>[0-9]+)$', UserProfileView.as_view(), name='user_profile'),
    url(r'^userprofile/(?P<pk>[0-9]+)/edit$', UserProfileUpdateView.as_view(),name='profile_edit'),
     url(r'^userprofile/(?P<pk>[0-9]+)/create$', UserProfileCreateView.as_view(),
        name='user_profile_create'),
    url(r'^post/(?P<pk>[0-9]+)/comment/(?P<pk_comment>[0-9]+)/edit$', CommentEditView.as_view(), name='comment_edit'),
    url(r'^post/(?P<pk>[0-9]+)/comment/(?P<pk_comment>[0-9]+)/delete$', CommentDeleteView.as_view(), name='comment_delete'),
    url(r'^post/(?P<pk>[0-9]+)/image/create$', UploadImage.as_view(), name='upload_image'),
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) 

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='profile')
    birthday = models.DateField(blank=True, null=True)
    first_name = models.CharField(max_length=33)
    last_name = models.CharField(max_length=33)
    
class Post(models.Model):
    text = models.CharField(max_length=200)
    profile_id = models.ForeignKey(UserProfile, related_name='profile')
    created_by = models.ForeignKey(User, related_name='posts')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} created by {} at {}".format(self.text, self.created_by.username, self.created_at)
        

class Image(models.Model):
    nume = models.CharField(max_length=200)
    image = models.ImageField(upload_to = 'images')
    post = models.ForeignKey(Post, related_name="images")
    added_at = models.DateTimeField(auto_now_add=True)
    added_by = models.ForeignKey(User, related_name='images')
    
    
class Comment(models.Model):
    text = models.CharField(max_length=200)
    post = models.ForeignKey(Post, related_name="comments")
    created_by = models.ForeignKey(User, related_name="comments")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} created by {} at {}".format(self.text, self.created_by.username, self.created_at)

blog/forms.py
from django import forms
from blog import models

class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ['text']
        
class UserProfileForm(forms.ModelForm):
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    e_mail = forms.CharField(max_length=100)
    class Meta:
        model =models.UserProfile
        exclude = ['user']

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

from django.views import View
from django.views.generic import TemplateView, ListView, DetailView
from models import Post, Comment, UserProfile, Image, User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse_lazy
# Create your views here.
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from forms import CommentForm,UserProfileForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from datetime import datetime 


def index(request):
    post_list = Post.objects.all()
    return render(request, 'index.html', {'post_list': post_list})

def post_detail(request, pk):
    post = Post.objects.get(id=pk)
    img = post.images.all()
    form = CommentForm()
    return render(request, "post_detail.html", 
    {"post": post, "img": img, "form": form})
    
class PostListView(ListView):
    template_name = 'index.html'
    model = Post
    context_object_name = 'post_list'
    
class PostCreateView( CreateView):
    model = Post
    fields = ['text']
    template_name = 'post_create.html'

    def form_valid(self, form):
        userProfile=UserProfile.objects.get(id=self.request.user.profile.id)
        post = Post.objects.create(
            created_by=self.request.user,
            profile_id=userProfile,
            **form.cleaned_data
        )
        return redirect(reverse_lazy("post_detail", kwargs={"pk": post.id }))

class PostEditView(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['text']
    template_name = 'post_update.html'

    def form_valid(self, form):
        post = Post.objects.get(pk=self.kwargs['pk'])
        post.text = form.cleaned_data['text']
        post.save()
        return redirect(reverse_lazy("post_detail", kwargs={"pk": self.kwargs['pk']}))
        
class PostDeleteView(LoginRequiredMixin, DeleteView):
    template_name = "post_delete.html"
    model = Post

    def get_success_url(self):
        return reverse_lazy('index')
    
class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ['text']
    
    def form_valid(self, form):
        post = Post.objects.get(id=self.kwargs['pk'])
        Comment.objects.create(
            created_by=self.request.user,
            post=post,
            **form.cleaned_data
        )
        return redirect(reverse_lazy("post_detail", kwargs={"pk": self.kwargs['pk']}))
        
class CommentEditView(LoginRequiredMixin, UpdateView):
    model = Comment
    fields = ['text']
    pk_url_kwarg = 'pk_comment'
    template_name = 'comment_update.html'

    def form_valid(self, form):
        comment = Comment.objects.get(pk=self.kwargs['pk_comment'])
        comment.text = form.cleaned_data['text']
        comment.save()
        return redirect(reverse_lazy("post_detail", kwargs={"pk": self.kwargs['pk']}))
        
class CommentDeleteView(LoginRequiredMixin, DeleteView):
    template_name = "comment_delete.html"
    model = Comment
    pk_url_kwarg = 'pk_comment'

    def get_success_url(self):
        return reverse_lazy("post_detail", kwargs={"pk": self.kwargs['pk']})


class UserProfileView(LoginRequiredMixin, DetailView):
    template_name = 'userprofile.html'
    model = UserProfile
    context_object_name = 'userprofile'

    def get_object(self):
        user = User.objects.get(id=self.kwargs['pk'])
        return user
        
class UserProfileCreateView( CreateView):
    model = UserProfile
    fields = ['birthday', 'first_name', 'last_name']
    template_name = 'user_profile_create.html'
    
    
    def form_valid(self, form):
        UserProfile.objects.create(
            user=self.request.user,
            **form.cleaned_data
        )
        return redirect(reverse_lazy("index"))
        
class UserProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = UserProfile
    form_class = UserProfileForm
    template_name = 'profile_update.html'

    def get_context_data(self, **kwargs):
        context = super(UserProfileUpdateView, self).get_context_data(**kwargs)
        user =  self.object.user
        context['form'].fields['first_name'].initial = user.first_name
        context['form'].fields['last_name'].initial = user.last_name
        context['form'].fields['e_mail'].initial = user.email
        return context

    def form_valid(self, form):
        data = form.cleaned_data
        self.object.birthday = data['birthday']
        self.request.user.first_name = data['first_name']
        self.request.user.last_name = data['last_name']
        self.request.user.email = data['e_mail']
        self.object.save()
        self.request.user.save()
        return redirect(reverse_lazy("user_profile",
                                     kwargs={"pk": self.request.user.id}))


class LoginView(TemplateView):
    template_name = 'login.html'

    def get_context_data(self):
        form = AuthenticationForm()
        return {'form': form}

    def post(self, request, *args, **kwargs):
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(username=data['username'],
                                password=data['password'])
            login(request, user)
            return redirect(reverse_lazy('index'))
        else:
            return render(request, "login.html", {"form": form})

class RegisterView(CreateView):
    template_name= 'register.html'
    form_class = UserCreationForm
    model = User

    def post(self, request, *args, **kwargs):
        form = UserCreationForm( data=request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = User.objects.create_user(username=data['username'],
                                        password=data['password1'])
            #UserProfile.objects.create(user=user)
            # import pdb; pdb.set_trace()
            user = authenticate(username=data['username'], password=data['password1'])
            login(request, user)
            return redirect(reverse_lazy("user_profile_create",
                                     kwargs={"pk": user.id}))
        else:
            return redirect('index')
        

class LogoutView(View):

    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect(reverse_lazy('index'))
        
class UploadImage(CreateView): 
    model = Image
    fields = ['nume','image']
    template_name = 'image_upload.html'

        
    def post(self, request, *args, **kwargs):
        # import pdb; pdb.set_trace()
        post = Post.objects.get(id = self.kwargs['pk'])
        Image.objects.create(
            added_by = self.request.user,
            post = post,
            image = request.FILES['image_path'])
        return redirect(reverse_lazy("post_detail", kwargs={"pk": self.kwargs['pk']}))

blog/templates/base.html
<html>
  <head>
     <title>
         {% block title %}
         {% endblock %}
     </title>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
     <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  </head>
  {% load static %}
  <body  style = "background-image: url( '{% static "/images/background.jpg" %}');">
    {% include 'nav.html' %}
    {% block content %}
    {% endblock %}
  </body>    
</html>

blog/templates/comment_delete.html
{% extends 'base.html' %}
{% block title %}
  Sterge comentariu
{% endblock%}

{% block content %}
<div class="card w-50 p-3 " style="left:300px;background: rgba(255,255,255,0.8); top: 100px; width:50%; padding: 16px;align-self:center;">
  <h5>Are you sure you want to delete this comment?</h5>
  <form method="post" class="form-inline">
    {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="Delete comment" />
  </form>
</div>
{% endblock %}

blog/templates/comment_update.html
{% extends 'base.html' %}
{% block title %}
  Edit comment
{% endblock%}

{% block content %}
  
   
  <form method="post" class="form-horizontal justify-content-center">
    {% csrf_token %}
    <div class="card w-50 p-3 " style="left:300px;background: rgba(255,255,255,0.8); top: 100px; width:50%; padding: 16px;align-self:center;">
     <div class="card-body" style="align-self:center;">
      <div class="form-group mx-2">
      <textarea rows="4" cols="50" class="form-control" type="text-area" 
      name="text" required="" id="id_text" maxlength="200">{{ form.text.initial }}</textarea>
    </div>
    <div style="text-align:center;">
    <input class="btn btn-secondary" type="submit" value="Update comment"/>
    </div>
  </div>
  </div>
  </form>
  
{% endblock %}

blog/templates/image_upload.html
{% extends 'base.html' %}

{% block title %} Serpentes Blog {% endblock %}

{% block content %}

    <form action="#" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="card" style="background: rgba(255,255,255,0.8); top: 100px; padding: 16px;width:40%;">
          <div class="form-group">
              <label for="nume">Nume:</label>
              <input type="text" name="nume" class="form-control" autofocus="" required="" id="nume" maxlength="150">
          </div>
    
          <div class="form-group">
              <label for="image_path">Imagine:</label>
              <input type="file" name="image_path" class="form-control" required="" id="image_path">
          </div>
        <input type="submit" class="btn btn-secondary" value="Add image" />
        </div>
    </form>
    
{% endblock %}

blog/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="card" style="background: rgba(255,255,255,0.8); top: 100px; padding: 16px;width:40%;">
  <h2>Login</h2>
  <form method="post" style="width:80%;">
    {% csrf_token %}
    <div class="form-group">
        {{ form.errors }}
    </div>
    
    <div class="form-group">
      <label for="id_username">Username:</label>
      <input type="text" name="username" class="form-control" autofocus="" required="" id="id_username" maxlength="150">
    </div>

    <div class="form-group">
      <label for="id_password">Password:</label>
      <input type="password" name="password" class="form-control" required="" id="id_password">
    </div>

    <button class="btn btn-primary" type="submit">Login</button>
    </div>
  </form>
{% endblock %}

blog/templates/nav.html
<ul class="nav" style="background: rgba(255,255,255,0.9);">
  <li class="nav-item">
    <a class="nav-link active" style="color: #000; font-weight: bold" href="{% url 'post_list' %}">Serpentes Blog</a>
  </li>
  {% if user.is_authenticated %}
    <li class="nav-item">
      <a class="nav-link active" style="color: #000; font-weight: bold" href="{% url 'user_profile' user.id %}">Hello, {{ user.username }}</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" style="color: #000; font-weight: bold" href="{% url 'logout' %}">Logout</a>
    </li>
    
     {% if user.is_superuser %}
    <li>
      <a class="nav-link active" style="color: #000; font-weight: bold" href="{% url 'admin:index' %}">Admin</a>
    </li>
    {% endif %} 
    
    <a href = "{% url 'post_create' user.id %}" class="btn btn-primary"> Create Post</a>
  {% else %}
    <li class="nav-item">
      <a class="nav-link active" style="color: #000; font-weight: bold" href="{% url 'login' %}">Login</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'register' %}">Register</a>
    </li>
  {% endif %}
</ul>

blog/templates/post_create.html
{% extends 'base.html' %}
{% block title %}
  Create post
{% endblock%}

{% block content %}
  <form method="post" class="form-inline justify-content-center">
    {% csrf_token %}
    <div class="card" style="background: rgba(255,255,255,0.8); top: 100px; padding: 16px;">
    <div class="form-group mx-2 card m-3">
      <textarea rows="4" cols="50" class="form-control" type="text-area" 
      name="text" required="" id="id_text" maxlength="200"></textarea>
    </div>
    <div class="m-2" style="text-align:center;">
    <input class="btn btn-secondary" type="submit" value="Create post" />
    </div>
    </div>
  </form>
{% endblock %}

blog/templates/post_delete.html
{% extends 'base.html' %}
{% block title %}
  Delete post
{% endblock%}

{% block content %}
<div class="card w-50 p-3 " style="left:300px;background: rgba(255,255,255,0.8); top: 100px; width:50%; padding: 16px;align-self:center;">
  <h5>Are you sure you want to delete the post?</h5>
  <form method="post" class="form-inline">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Delete post" />
  </form>
</div>
{% endblock %}

blog/templates/post_detail.html
{% extends 'base.html' %}
{% block title %}
  {{ post.text }}
{% endblock%}

{% block content %}
<div class="container">
  <div class="p-3">
    <div class="card" style="background: rgba(255,255,255,0.8); top: 100px; padding: 16px;">
      <div class="card-body">
        <h1 class="card-title">{{ post.text }}</h1>
        <p class="card-text">Created by:
          <a href="{% url 'user_profile' post.created_by.id %}">{{ post.created_by.username }}</a>
        </p>
        <div class="m-2">
      {% if user == post.created_by %}
        <a class="btn btn-secondary" href="{% url 'post_edit' post.id %}">Edit post</a>
        <a class="btn btn-secondary" href="{% url 'post_delete' post.id %}">Delete post</a>
        <a class="btn btn-secondary" href="{% url 'upload_image' pk=post.id %}">Upload Image</a>
      {% endif %}
      <br>
      <hr>
      {% if post.images.all %}
      {% for image_group in img %}
          <img src = "{{ image_group.image.url }}" alt = "{{image_group.image}}" width = 300 height = 300 />
        {% endfor %}
    {% endif %}
    </div>
      </div>
      <div class="card-footer text-muted">
        {{ post.created_at }}
      </div>
    </div>

    

  </div>
  <div class="container">
  <div class="p-3">
  <div class="card" style="background: rgba(255,255,255,0.8); top: 100px; padding: 16px;">
    <div class="card-body">
    <h2>Comments</h2>
    <div class="card-footer text-muted">
    {% if user.is_authenticated %}
    <form action="{% url 'comment_create' post.id %}" method="post" class="form-inline ">
      {% csrf_token %}
      <!--{{ form.as_p }}-->
      <div class="form-group mx-2">
        <input class="form-control" type="text" name="text" required="" id="id_text" maxlength="200">
      </div>
      <input class="btn btn-secondary" type="submit" value="Comment" />
    </form>
    {% endif %}
    
    
    {% if post.comments.all %}
      {% regroup post.comments.all|dictsortreversed:"created_at" by created_at as comments %}
      {% for comment_group in comments %}
        {% for comment in comment_group.list %}
        <div class="card m-3">
          
          <div class="card-body">
            <blockquote class="blockquote mb-0">
              <p>
                {{ comment.text }}
                {% if comment.created_at|date:"Y-m-d H:M" !=  comment.updated_at|date:"Y-m-d H:M" %}
                  <small><i>(edited)</i></small>
                {% endif %}
              </p>
              <footer class="blockquote-footer">commented by
                <cite><a href="{% url 'user_profile' comment.created_by.id %}">{{ comment.created_by.username }}</a></cite>
                on <cite>{{ comment.created_at }}</cite>
              </footer>
              
            </blockquote>
            <div class="m-2 ">
              <a class="btn btn-secondary" href="{% url 'comment_edit' post.id comment.id %}">Edit comment</a>
              <a class="btn btn-secondary" href="{% url 'comment_delete' post.id comment.id %}">Delete comment</a>
            </div>
          </div>
        </div>
        {% endfor%}
      {% endfor %}
    {% else %}
      <p class="font-italic"> No comments yet.</p>
    {% endif %}
  </div>
  </div>
  </div>
  </div>
  </div>
</div>
{% endblock %}

blog/templates/post_update.html
{% extends 'base.html' %}
{% block title %}
  Edit post
{% endblock%}

{% block content %}
  <form method="post" class="form-inline justify-content-center">
    {% csrf_token %}
    <div class="card" style="background: rgba(255,255,255,0.8); top: 100px; padding: 16px;width:40%;">
    <div class="form-group ">
      <textarea rows="4" cols="50" class="form-control" type="text-area" 
      name="text" required="" id="id_text" maxlength="200">{{ form.text.initial }}</textarea>
    </div>
    <br>
    <div style="text-align:center;">
      <input class="btn btn-secondary" style="width:50%;" type="submit" value="Update post" />
    </div>
    </div>
  </form>
{% endblock %}

blog/templates/profile_update.html
{% extends 'base.html' %}
{% block title %}
  
{% endblock%}

{% block content %}

  <form method="post" class="justify-content-center ">
    <div class="card" style="background: rgba(255,255,255,0.8); top: 100px; padding: 16px;width:40%;">
  <h2 style="text-align:center;">Edit profile</h2>
    {% csrf_token %}
    {{ form.errors }}
    <div class="form-group mx-2">
      <label for="id_birthday">Birthday:</label>
      <input type="text" name="birthday" class="form-control"
             value="{{ form.birthday.initial | date:'Y-m-d' }}" id="id_birthday">
    </div>

    <div class="form-group mx-2">
      <label for="id_first_name">First name:</label>
      <input type="text" class="form-control" name="first_name" 
             value="{{ form.first_name.initial }}" required="" id="id_first_name" 
             maxlength="100">
    </div>

    <div class="form-group mx-2">
      <label for="id_last_name">Last name:</label>
      <input type="text" class="form-control" name="last_name" 
             required="" id="id_last_name" maxlength="100" 
             value="{{ form.last_name.initial }}">
    </div>

    <div class="form-group mx-2">
      <label for="id_e_mail">E-mail:</label>
      <input type="text"  class="form-control" name="e_mail" 
             required="" id="id_e_mail" maxlength="100"
             value="{{ form.e_mail.initial }}">
    </div>
    <div class="form-group mx-2">
    <input class="btn btn-secondary" type="submit" value="Update profile" />
    </div>
    </div>
  </form>
  
{% endblock %}

blog/templates/register.html
{% extends 'base.html' %}

{% block content %}
  <h2>Register</h2>
  <form method="post" class="form-inline justify-content-center text-center">
    {% csrf_token %}
    <div class="form-group justify-content-center">
        {{ form.errors }}
    </div>
    <div class="card" style="background: rgba(255,255,255,0.8); top: 100px; padding: 16px;">
      <h2 class="text-center"> Register</h2>
    <div class="form-group" style="padding: 16px;">
      <label class="control-label col-sm-4" for="id_username">Username:</label>
      <div class="col-sm-8">
        <input  type="text" name="username" class="form-control" autofocus="" required="" id="id_username" maxlength="150">
      </div>
    </div>
    
    <div class="form-group" style="padding: 16px;">
      <label class="control-label col-sm-4" for="id_password1">Password:</label>
      <div class="col-sm-8">
        <input type="password" name="password1" class="form-control" required="" id="id_password1">
      </div>
    </div>
    
    <div class="form-group" style="padding: 16px;">
      <label class="control-label col-sm-4" for="id_password2">Password confirmation:</label>
      <div class="col-sm-8">
      <input type="password" name="password2" class="form-control" required="" id="id_password2">
      </div>
    </div>
    
    
    <div class="text-center">
      <button class="btn btn-primary center-block btn-sd" type="submit">Register</button>
    </div>
    </div>
  </form>
{% endblock %}

blog/templates/user_profile_create.html
{% extends 'base.html' %}
{% block title %}
  Create profile
{% endblock%}

{% block content %}
  <form method="post" class="form-inline justify-content-center">
    {% csrf_token %}
    <div class="card" style="background: rgba(255,255,255,0.8); top: 100px; padding: 16px;">
     <h2 class="text-center">Create your profile</h2>
    <div class="form-group mx-2" style="padding: 16px;">
        <label  class="control-label col-sm-4" for="id_first_name">First name: </label>
        <div class="col-sm-8">
            <input type="text" name="first_name" class="form-control" required="" id="id_first_name">
        </div>
    </div>
    <div class="form-group mx-2" style="padding: 16px;">
        <label class="control-label col-sm-4" for="id_last_name">Last name: </label>
        <div class="col-sm-8">
            <input type="text" name="last_name" class="form-control" required="" id="id_last_name">
        </div>
    </div>
    <div class="form-group mx-2" style="padding: 16px;">
      <label class="control-label col-sm-4" for="id_birthday">Birthday: </label>
      <div class="col-sm-8">
          <input type="date" name="birthday" min="1918-01-01" class="form-control" required="" id="id_birthday">
        </div>
    </div>
    <div class="text-center">
        <input class="btn btn-secondary btn-success" style="padding: 16px;" type="submit" value="Create profile" />
    </div>
    </div>
  </form>
{% endblock %}

blog/templates/userprofile.html
{% extends 'base.html' %}

{% block title %} User Profile - {{ userprofile.username }} {% endblock %}

{% block content %}
<div class="card" style="background: rgba(255,255,255,0.8); top: 100px; padding: 16px;width:40%;">
  <h1>{{ userprofile.username }}' Profile</h1>
    <ul class="list-group m-4">
      <li class="list-group-item"><b>Fullname:</b> {{ userprofile.first_name }} </li>
      <li class="list-group-item"><b>Username:</b> {{ userprofile.username }}</li>
      <li class="list-group-item"><b>E-mail:</b> {{ userprofile.email }}</li>
      <li class="list-group-item"><b>Birthday:</b> {{ userprofile.profile.birthday }}</li>
    </ul>
   <div class="m-2">
      <a class="btn btn-primary" href="{% url 'profile_edit' user.profile.id %}">Edit profile</a>
    </div>
  </div>
{% endblock %}